### ISSUE TITLE
cmake compile failed

### ISSUE THREAD

**Issue by LIZHICHAOUNICORN** [topcpporg/raftcpp#44]
I git clone raftcpp and  build project by following readme, but I got this error:

ENV:
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Linux aliyun 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

![error](https://user-images.githubusercontent.com/18499529/90845957-c1d9cf80-e399-11ea-8f69-9a8e469da837.png)

**Comment by jovany-wang** [comment]
Thanks for reporting this, I post a PR to fix it. #45
