### ISSUE TITLE
Add ID classes

### ISSUE THREAD

**Issue by jovany-wang** [topcpporg/raftcpp#94]

**Comment by vasantteja** [comment]
Can I assign this issue?

**Comment by jovany-wang** [comment]
Hi @vasantteja ,  This https://github.com/topcpporg/raftcpp/pull/123 had already finished the `NodeID`. 

If you're interested in the further enhancements on this,  I think you can do these works:
(1) Refine this `NodeID` to let it extends from a `BaseID`.
(2) Add a `TermID` class extending from `BaseID`.

How do you think of it?

**Comment by jovany-wang** [comment]
#124 closes this.
